DROP TABLE BOARD;
CREATE TABLE BOARD(
    BNUMBER NUMBER CONSTRAINT PK_BNUM PRIMARY KEY,
    BWRITER NVARCHAR2(10),
    BTITLE NVARCHAR2(30),
    BCONTENTS NVARCHAR2(1000),
    BDATE DATE,
    BHITS NUMBER);

CREATE SEQUENCE BOARD_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
drop sequence BOARD_SEQ;

show user;
DROP TABLE BOARD1;
SELECT * FROM BOARD;
SELECT * FROM BOARD WHERE BTITLE LIKE '%the%';
commit; 

ALTER TABLE BOARD ADD BFILENAME NVARCHAR2(50);
COMMIT;